site_name: 24çº§å·¥è¯•å­¦é•¿ç»„èµ„æ–™æ±‡æ€»
site_author: 24çº§å·¥è¯•å­¦é•¿ç»„
site_url: https://zju-enginpilot.github.io/Kickstart2024/
site_description: 24çº§å·¥è¯•å­¦é•¿ç»„èµ„æ–™æ±‡æ€»ç½‘ç«™

repo_name: Kickstart2024
repo_url: https://github.com/ZJU-EnginPilot/Kickstart2024
edit_uri: tree/main/docs/

copyright: Copyright &copy; 2024 æµ™æ±Ÿå¤§å­¦å·¥ç§‘è¯•éªŒç­å­¦é•¿ç»„

theme:
  name: material
  language: zh
  favicon: images/LOGO.png
  icon:
    logo: material/book-education-outline
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/file-eye-outline
  custom_dir: overrides
  features:
    - navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.tabs
    - navigation.top
    - navigation.indexes  # ç‚¹å‡»å°èŠ‚åå­—è‡ªåŠ¨æ˜¾ç¤º index ç•Œé¢
    - navigation.footer # åº•éƒ¨å¯¼èˆªæ 
    - navigation.instant # ç«™å†…ç¬ç§»
    - navigation.instant.progress
    - toc.integrate   # å•æ  toc
    - toc.follow  # å³ä¾§ç›®å½•è·Ÿéšæ»šåŠ¨
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit # git edit page
    - content.tooltips
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"  # æµ…è‰²æ¨¡å¼
      scheme: default
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢åˆ°æ·±è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"   # æ·±è‰²æ¨¡å¼
      scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼

  font:
    text: Roboto
    code: Roboto Mono

extra:
  analytics:
    provider: google
    property: G-9WENM1FP2P
    feedback:
      title: è¿™ä¸ªé¡µé¢å¯¹ä½ æœ‰å¸®åŠ©å—ï¼Ÿ
      ratings:
        - icon: material/thumb-up-outline
          name: å¸®åŠ©å¾ˆå¤§ï¼
          data: 1
          note: >-
            æ„Ÿè°¢ä½ çš„åé¦ˆï¼ğŸ˜˜
        - icon: material/thumb-down-outline
          name: æœ‰å¾…æ”¹è¿›ï¼
          data: 0
          note: >- 
            æ„Ÿè°¢ä½ çš„åé¦ˆ! ä¸ºè¿™ä¸ªç½‘ç«™é¡¹ç›®åš<a href="https://zju-enginpilot.github.io/Kickstart2024/contribution/" target="_blank" rel="noopener">è´¡çŒ®</a>ï¼Œ
            ä¸€èµ·è®©å®ƒå˜å¾—æ›´å¥½ï¼ğŸš€

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date
  - git-committers:
      enabled: !ENV [CI, false]
      repository: ZJU-EnginPilot/Kickstart2024
      branch: main
  - minify:
      minify_html: true # åŠ å¿«ç½‘é¡µåŠ è½½é€Ÿåº¦
  - statistics:
      page_check_metadata: comment

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js   # MathJax 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

nav:
  - ä¸»é¡µ: 
    - "index.md"
    - æœ‰é—®é¢˜é—®è°ï¼Ÿ: "contact.md"
    - å¦‚ä½•è´¡çŒ®: "contribution.md"
    - å‹æƒ…é“¾æ¥: "links.md"
  - å…¥å­¦ !:
    - "Enroll/index.md"
    - å…¥å­¦å‰å‡†å¤‡: "Enroll/Preparation.md"
    - æŠ¥åˆ°: "Enroll/Orientation.md"
  - å†›è®­:
    - "MT/index.md"
    - å†›è®­æ—¥ç¨‹: "MT/Schedule.md"
    - å†›è®­æ´»åŠ¨: "MT/Activities.md"
    - æ³¨æ„äº‹é¡¹: "MT/Note.md"
    - è€ƒæ ¸: "MT/Assessment.md"
  - å­¦ä¹ :
    - "Study/index.md"
    - å­¦ä¸šåŸºæœ¬åˆ¶åº¦: "Study/Concepts.md"
    - ä½“è‚²: "Study/PE.md"
    - é€‰è¯¾: "Study/CourseSelection.md"
    - å·¥è¯•è¯¾ç¨‹ç»éªŒ: "Study/Courses.md"
    - å·¥è¯•ä¸“ä¸šç®€ä»‹: "Study/Majors.md"
    - ä¸“ä¸šé€‰æ‹©: "Study/MajorSelection.md"
  - ç”Ÿæ´»: 
    - "Life/index.md"
    - å®‰å…¨: "Life/Safety.md"
    - è¡£: "Life/Clothes.md"
    - é£Ÿ: "Life/Food.md"
    - ä½: "Life/Accommodation.md"
    - è¡Œ: "Life/Transportation.md"
    # - æ¸¸: "Life/Entertainment.md"
    - é‡è¦åœ°ç‚¹: "Life/Places.md"
    - æ´»åŠ¨: "Life/Activities.md"
    - ç¤¾å›¢ç»„ç»‡: "Life/Clubs.md"
  - çº¿ä¸Šå¹³å°:
    - "Online/index.md"
    - æ ¡å›­ç½‘: "Online/ZJUNet.md"
    - æµ™å¤§é’‰: "Online/ZJUDing.md"
    - è½¯ä»¶ï¼ˆAPPï¼‰: "Online/APP.md"
    - å¾®ä¿¡å…¬ä¼—å·: "Online/WeChat.md"
    - å­¦ä¹ å¹³å°: "Online/Learning.md"
    - è®ºå›: "Online/Forum.md"
    - å…¶ä»–: "Online/Others.md"
  # - æŠ€èƒ½: 
  #   - "Skills/index.md"
  #   - ç”µè„‘åŸºæœ¬æ“ä½œ: "Skills/PCop.md"
  - æ‹“å±•é˜…è¯»: "More/index.md"